# Generated by Django 3.2.19 on 2024-02-15 19:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='../images/accountImages/default-account-img.jpeg', force_format='JPEG', keep_meta=False, quality=90, scale=None, size=[150, 150], upload_to='images/accountImages/'),
        ),
    ]
