# Generated by Django 3.2.19 on 2024-02-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('zodiac_sign', models.CharField(choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=50)),
                ('relationship', models.CharField(choices=[('Friendship', 'Friendship'), ('Romantic Relationship', 'Romantic Relationship'), ('Dating', 'Dating'), ('Married', 'Married')], max_length=50)),
                ('characteristics', models.CharField(choices=[('Introverted', 'Introverted'), ('Extroverted', 'Extroverted'), ('Shy', 'Shy'), ('Self-Confident', 'Self-Confident'), ('Grumpy', 'Grumpy'), ('Heartful', 'Heartful'), ('Compassionate', 'Compassionate'), ('Loyal', 'Loyal'), ('Disloyal', 'Disloyal'), ('Open-minded', 'Open-minded'), ('Curious', 'Curious'), ('Generous', 'Generous')], max_length=50)),
                ('interests', models.CharField(choices=[('Sports', 'Sports'), ('Gaming', 'Gaming'), ('Animals', 'Animals'), ('Eating', 'Eating'), ('Open-minded', 'Open-minded'), ('Travelling', 'Travelling'), ('Studying', 'Studying'), ('Arts', 'Arts'), ('Music', 'Music'), ('Drinking', 'Drinking'), ('Nature', 'Nature'), ('Coding', 'Coding')], max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
