# Generated by Django 3.2.19 on 2024-02-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerprofile',
            old_name='account',
            new_name='owner',
        ),
    ]
