# Generated by Django 3.2.19 on 2024-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerprofile', '0002_rename_account_partnerprofile_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerprofile',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='DOB',
            field=models.CharField(default=18, max_length=50),
            preserve_default=False,
        ),
    ]
