# Generated by Django 3.2.19 on 2024-02-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerprofile', '0003_auto_20240218_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='DOB',
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='age',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
