# Generated by Django 3.2.19 on 2024-02-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerprofile', '0004_auto_20240218_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerprofile',
            old_name='created_by',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
