# Generated by Django 3.2.19 on 2024-02-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerprofile', '0005_auto_20240218_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='characteristics',
            field=models.CharField(blank=True, choices=[('Introverted', 'Introverted'), ('Extroverted', 'Extroverted'), ('Shy', 'Shy'), ('Self-Confident', 'Self-Confident'), ('Grumpy', 'Grumpy'), ('Heartful', 'Heartful'), ('Compassionate', 'Compassionate'), ('Loyal', 'Loyal'), ('Disloyal', 'Disloyal'), ('Open-minded', 'Open-minded'), ('Curious', 'Curious'), ('Generous', 'Generous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='interests',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('Gaming', 'Gaming'), ('Animals', 'Animals'), ('Eating', 'Eating'), ('Open-minded', 'Open-minded'), ('Travelling', 'Travelling'), ('Studying', 'Studying'), ('Arts', 'Arts'), ('Music', 'Music'), ('Drinking', 'Drinking'), ('Nature', 'Nature'), ('Coding', 'Coding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Friendship', 'Friendship'), ('Romantic Relationship', 'Romantic Relationship'), ('Dating', 'Dating'), ('Married', 'Married')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='zodiac_sign',
            field=models.CharField(blank=True, choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=50),
        ),
    ]
